kyma-test-infra-dev/test-infra

- prow/config.yaml
- prow/jobs/kyma/kyma-integration.yaml
> changed repo

- prow/jobs/kyma/kyma-integration.yaml
> aks-nightly every two hours.

- prow/config.yaml
- prow/jobs/kyma/kyma-integration.yaml
correct repositories paths
- ...
- ...
- ...
> correct preset

- prow/config.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/plugins.yaml
set aks-nightly to run daily at 4 am.
> Changed aks build schedule to daily at 4 am.

- prow/config.yaml
> Changed container registry to point to neighbors dev project.

- prow/config.yaml
> fix logo and favicon on deck

- prow/cluster/03-tls-ing_ingress.yaml
- prow/cluster/11-gcsweb.yaml
- prow/config.yaml
Disabled tls in ingress with gce ingress-class.
Changed bucket in gcsweb deployment.
Changed IPs to hostnames.
- ...
- ...
- ...
> Changed hostnames in ingress def.

- prow/config.yaml
> corrected urls.

- prow/cluster/11-gcsweb.yaml
> disabled gcsweb upgrade to https.

- development/prow-installer/config/cluster/03-tls-ing_ingress.yaml
> corrected gcsweb URL.

- development/prow-installer/config/cluster/00-deck-patch.yaml
- development/prow-installer/config/cluster/06-pushgateway_deployment.yaml
- development/prow-installer/config/cluster/10-ghproxy.yaml
- development/prow-installer/config/cluster/starter.yaml
- prow/config.yaml
enabled debug log level
- ...
- ...
- ...
> added missing args.

- prow/config.yaml
> corrected header color def

- prow/config.yaml
> removed duplicated preset definition

- prow/jobs/kyma/kyma-integration.yaml
- prow/scripts/fail_test_job.sh
- prow/scripts/success_test_job.sh
added execution permission on scripts.
- ...
- ...
- ...
> enabled run-always optional success.

- prow/config.yaml
- prow/jobs/kyma/kyma-integration.yaml
added required contexts
- ...
- ...
- ...
> changed names to be more explanatory

- prow/config.yaml
- prow/jobs/kyma/kyma-integration.yaml
> branch protector test

- prow/plugins.yaml
> enabled prow to report skipped jobs

- development/jobguard/cmd/main.go
- development/jobguard/go.mod
- development/jobguard/pkg/filter.go
- development/jobguard/pkg/httpclient.go
- development/jobguard/pkg/status.go
- development/jobguard/pkg/waiter.go
- prow/config.yaml
> jobguard package path fix

- prow/jobs/kyma/kyma-integration.yaml
> trigger pre-master-gke-kyma-integration on test_success changes

- prow/jobs/kyma/kyma-governance.yaml
- prow/jobs/kyma/kyma-integration.yaml
- prow/jobs/kyma/kyma-kind-integration.yaml
- prow/jobs/kyma/kyma-vulnerability-scanner.yaml
> disabled periodic jobs.

- prow/jobs/community/community-governance.yaml
- prow/jobs/scans/whitesource-periodics.yaml
- prow/jobs/test-infra/test-infra-governance.yaml
- prow/jobs/website/website-governance.yaml
> disabled periodics

- prow/jobs/kyma/kyma-integration-gardener-azure.yaml
- prow/jobs/kyma/kyma-integration-gardener-gcp.yaml
> disabled gardener jobs

- prow/jobs/cli/cli-integration.yaml
> disabled periodic

- prow/cluster/components/15-deck_deployment.yaml
> Rerun button

- prow/staging/jobs/presubmit.yaml
- prow/staging/plugins.yaml
> test changes

- prow/staging/jobs/autobump.yaml
> More updates

- prow/staging/config.yaml
> remove repo branch protection

- prow/staging/config.yaml
- prow/staging/plugins.yaml
> invalidcommitmsg plugin
